# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc8148b6e8b1e94cd7e4457c5b5734b4c572430bc457a27ab546d134ad521cea85ebf4c4656c21f932e0db768f03015f974d6557b4a9699e73f695909557a7db

test:
  secret_key_base: 1363ce4b8ca8af67746790fd46641ab7b3f3861aa8994b19c8a7c6cac3299b327f00a809030ae63034e813772c566550951c83bbdd157f1154f73fb51a60da56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
